### ISSUE TITLE
The package 1.8.2-DSM6-RC does not start

### ISSUE THREAD

**Issue by krzychb** [openhab/openhab-syno-spk#19]
Model name: DS414 
CPU: MARVELL Armada XP MV78230 
DSM version: DSM 6.0-7321 
Java: 1.8.0_077

Hi @cniweb,

The package 1.8.2-DSM6-RC does not start automatically after installation.
It does not start as well after pressing "Run".
There are no messages in "View Log".
Please find attached synopkg.log - [synopkg.log.txt](https://github.com/openhab/openhab-syno-spk/files/192153/synopkg.log.txt)

Using ssh I have attempted to run start.sh manually. The result is as below.

```
root@NaszDysk:/volume1/@appstore/OpenHAB# ls -l
total 68
lrwxrwxrwx 1 openhab root     30 Mar 28 17:17 addons -> /volume1/public/OpenHAB/addons
lrwxrwxrwx 1 openhab root     38 Mar 28 17:17 configurations -> /volume1/public/OpenHAB/configurations
drwxrwxrwx 2 openhab users  4096 Mar 28 17:17 contexts
drwxrwxrwx 2 openhab users  4096 Mar 28 17:17 etc
-rwxrwxrwx 1 openhab users 11232 Mar 21 20:44 LICENSE.TXT
drwxr-xr-x 2 openhab users  4096 Mar 28 17:18 logs
-rwxrwxrwx 1 openhab users   652 Mar 21 20:44 README.TXT
drwxrwxrwx 6 openhab users  4096 Mar 28 17:17 server
drwxrwxrwx 2 openhab users  4096 Mar 28 17:17 sounds
-rwxrwxrwx 1 openhab users   996 Mar 21 20:44 start.bat
-rwxrwxrwx 1 openhab users  1146 Mar 21 20:44 start_debug.bat
-rwxr-xr-x 1 openhab root   1132 Nov 17  2013 start_debug_runtime.sh
-rwxrwxrwx 1 openhab users  1132 Mar 21 20:44 start_debug.sh
-rwxr-xr-x 1 openhab root    930 Nov 17  2013 start_runtime.sh
-rwxrwxrwx 1 openhab users   969 Mar 21 20:44 start.sh
-rwxr-xr-x 1 openhab root     65 Nov 17  2013 stop_runtime.sh
drwxrwxrwx 4 openhab users  4096 Mar 28 17:17 webapps
root@NaszDysk:/volume1/@appstore/OpenHAB# ./start.sh
Launching the openHAB runtime...
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
        at sun.nio.cs.UTF_8$Decoder.decode(UTF_8.java:441)
        at java.lang.StringCoding$StringDecoder.decode(StringCoding.java:153)
        at java.lang.StringCoding.decode(StringCoding.java:193)
        (...)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
root@NaszDysk:/volume1/@appstore/OpenHAB#

```

The OpenHAB was running correctly with previous DSM 5.2 package. 
Now It looks like I am missing something with new DSM 6.0.  

What can I do to troubleshoot this issue?

Krzysztof

**Comment by krzychb** [comment]
After returning to this issue on next day I decided to check my Java installation. So far I have been installing Java provided by http://pcloadletter.co.uk/2011/08/23/java-package-for-synology/. This has been working for me without any issues for last two years or so.

Now I have discovered that together with DSM 6.0, Synology is providing build in Java installer.
It is available in Package Center under Developer Tools. I have decided to try it instead.

As you may guess this made the trick.

Apparently installation by http://pcloadletter.co.uk/ does not yet support DSM 6.0.

Krzysztof
