### ISSUE TITLE
karaf console not running on OH2 

### ISSUE THREAD

**Issue by gorzan14** [openhab/openhab-syno-spk#51]
Karaf console does not start and is not reachable. Everything is doing well on OH2.

2017-01-28 12:57:40.437 [WARN ] [org.apache.karaf.shell.ssh.Activator] - Exception caught while starting SSH server
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)[:1.8.0_92]
	at sun.nio.ch.Net.bind(Net.java:433)[:1.8.0_92]
	at sun.nio.ch.Net.bind(Net.java:425)[:1.8.0_92]
	at sun.nio.ch.AsynchronousServerSocketChannelImpl.bind(AsynchronousServerSocketChannelImpl.java:162)[:1.8.0_92]
	at org.apache.sshd.common.io.nio2.Nio2Acceptor.bind(Nio2Acceptor.java:66)[61:org.apache.sshd.core:0.14.0]
	at org.apache.sshd.common.io.nio2.Nio2Acceptor.bind(Nio2Acceptor.java:74)[61:org.apache.sshd.core:0.14.0]
	at org.apache.sshd.SshServer.start(SshServer.java:287)[61:org.apache.sshd.core:0.14.0]
	at org.apache.karaf.shell.ssh.Activator.doStart(Activator.java:117)[56:org.apache.karaf.shell.ssh:4.0.8]
	at org.apache.karaf.util.tracker.BaseActivator.run(BaseActivator.java:246)[56:org.apache.karaf.shell.ssh:4.0.8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_92]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_92]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_92]

**Comment by cniweb** [comment]
`Address already in use` you have run a another process with port binding!

**Comment by gorzan14** [comment]
Netstat does Not schow any of the karaf Ports 8081, 5005, 44444 in use.

I use homematic1, astro1, Hue, prowl1 Bindung. 

Von meinem iPhone gesendet

**Comment by cniweb** [comment]
`2017-01-28 12:57:40.437 [WARN ] [org.apache.karaf.shell.ssh.Activator] - Exception caught while starting SSH server
java.net.BindException: Address already in use`
Default port = 8101
See docu: http://docs.openhab.org/administration/console.html

**Comment by gorzan14** [comment]
Thanks for the Docs. 

When I stop all packages in my syno karaf works. Up to know i couldnt find which one is the bad one and which port it uses that karaf wants.

**Comment by gorzan14** [comment]
By try and error (stop OH, stop one package, start OH) i found after a while the bad package:
DVBLink Server. 
It was possible to change the port 8101 on both DVBLink (at web config page) and OH (at karaf config file). Both where successfull after manually restarting the package. 

Thanks for help. @cniweb you can close this issue.
